describe('metamask', () => {
    describe('walletEnable', () => {})
    describe('walletGetSnaps', () => {})
    describe('WalletRequestSnaps', () => {})
    describe('walletInvokeSnap', () => {})
    describe('walletSnap', () => {})
    describe('snapDialog', () => {})
    describe('snapGetBIP44Entropy', () => {})
    describe('snapManageState', () => {})
    describe('snapNotify', () => {})
})